### ISSUE TITLE
Tekrar eden kodlar azaltılmalı 

### ISSUE THREAD

**Issue by fatihcode** [fatihoz5758/email#1]
Tekar eden kodları tek bir class altında toparlayıp her dive iki class şeklinde verilebilir.

Örnek olması için html ve css dosyalarını aşağıdaki şekilde yazdım. 

``` html
<div class="box box1">
....
</div>
```

```css

.box{
    border-radius: 20px;
    font-size: 24px;
    padding: 30px;
    font-weight: bold;
    margin-bottom: 20px;
    text-align: center;
}

.box1 {
    background-color: #d5d3d5;
    color: #420aa8;
}

.box2 {
    background-color: #c962c9;
    color: #133605;
}

.box3 {
    background-color: #7aacec;
    font-size: 24px;
    padding: 10px;
    color: #1b0669;
    margin-bottom: 30px;
    text-align: right;
    font-family: 'Sevillana';
}
```

Eline sağlık güzel olmuş.
